
spring:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: '*'
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PDB_HOST:localhost}:${PDB_PORT:16603}/${PDB_DB_NAME}
    username: ${PDB_USERNAME}
    password: ${PDB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
#  spring.mail.host=localhost
#  spring.mail.port=1025
#  spring.mail.username=hello
#  spring.mail.password=hello
#  spring.mail.properties.mail.smtp.ssl.trust=*
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.connectiontimeout=5000
#  spring.mail.properties.mail.smtp.timeout=3000
#  spring.mail.properties.mail.smtp.writetimeout=5000