
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PDB_HOST:localhost}:${PDB_PORT:3306}/${PDB_DB_NAME}
    username: ${PDB_USERNAME}
    password: ${PDB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update